// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskService.Infrastructure.Persistence;

#nullable disable

namespace TaskService.Infrastructure.Migrations
{
    [DbContext(typeof(TaskServiceDbContext))]
    [Migration("20260322135056_FixWorkspaceMemberPrimaryKey")]
    partial class FixWorkspaceMemberPrimaryKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaskService.Domain.Entities.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("UploaderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.HasIndex("UploaderId");

                    b.ToTable("Attachments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019d15d0-2453-7457-94c0-44e362d84585"),
                            IssueId = new Guid("019d15d0-2453-7233-b651-43e60963115f"),
                            StoragePath = "issues/taskorium-api/openapi-staging/checklist.pdf",
                            UploaderId = new Guid("019d15d0-2452-7c53-a3d0-d4c7853bc4fa")
                        },
                        new
                        {
                            Id = new Guid("019d15d0-2454-7d76-97a5-eafa1c2a255a"),
                            IssueId = new Guid("019d15d0-2453-7429-a8bb-ebd126ee1fe2"),
                            StoragePath = "issues/ui-kit/dialog-focus/nested-dialog-repro.webm",
                            UploaderId = new Guid("019d15d0-2452-72aa-a7bd-1805328e4efa")
                        });
                });

            modelBuilder.Entity("TaskService.Domain.Entities.Issue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IssueStatusId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IssueTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(225)
                        .HasColumnType("character varying(225)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ResolvedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Issues");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019d15d0-2453-7233-b651-43e60963115f"),
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 3, 22, 13, 50, 55, 571, DateTimeKind.Unspecified).AddTicks(8823), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Generate and upload the merged spec to the docs bucket; add link from the repo README.",
                            DueDate = new DateTimeOffset(new DateTime(2025, 3, 28, 17, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IssueStatusId = new Guid("019d15d0-2453-7dd0-a9d5-4853949a08ac"),
                            IssueTypeId = new Guid("019d15d0-2453-7d9f-bfaa-133df11a0f3d"),
                            Name = "Publish OpenAPI 3.1 bundle for staging",
                            ProjectId = new Guid("019d15d0-2453-7a57-8998-a9493767fd5c")
                        },
                        new
                        {
                            Id = new Guid("019d15d0-2453-77ad-b26a-21c31bfd02c6"),
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 3, 22, 13, 50, 55, 571, DateTimeKind.Unspecified).AddTicks(9324), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Repro: list issues with page size 50; next cursor sometimes returns 400. Add regression test against snapshot payloads.",
                            DueDate = new DateTimeOffset(new DateTime(2025, 3, 22, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IssueStatusId = new Guid("019d15d0-2453-7415-b462-5eb7fb31a500"),
                            IssueTypeId = new Guid("019d15d0-2453-7aa0-abb6-29a434a8748c"),
                            Name = "Fix inconsistent cursor encoding on issue list",
                            ProjectId = new Guid("019d15d0-2453-7a57-8998-a9493767fd5c")
                        },
                        new
                        {
                            Id = new Guid("019d15d0-2453-75c4-99f6-14ce1cdeb20d"),
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 3, 22, 13, 50, 55, 571, DateTimeKind.Unspecified).AddTicks(9326), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Align with product spec: max 8 attempts, jitter, dead-letter after final failure.",
                            DueDate = new DateTimeOffset(new DateTime(2025, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IssueStatusId = new Guid("019d15d0-2453-733e-982b-cc29b085b551"),
                            IssueTypeId = new Guid("019d15d0-2453-73c7-ba12-42afb64f3541"),
                            Name = "Webhook delivery retries with exponential backoff",
                            ProjectId = new Guid("019d15d0-2453-7a57-8998-a9493767fd5c")
                        },
                        new
                        {
                            Id = new Guid("019d15d0-2453-7bcd-b69d-486507755841"),
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 3, 22, 13, 50, 55, 571, DateTimeKind.Unspecified).AddTicks(9327), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Expose SQL and message bus connectivity in /health/detailed for k8s probes.",
                            IssueStatusId = new Guid("019d15d0-2453-75ce-8a81-034b0f24caea"),
                            IssueTypeId = new Guid("019d15d0-2453-73c7-ba12-42afb64f3541"),
                            Name = "Health checks return dependency status",
                            ProjectId = new Guid("019d15d0-2453-7a57-8998-a9493767fd5c")
                        },
                        new
                        {
                            Id = new Guid("019d15d0-2453-7429-a8bb-ebd126ee1fe2"),
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 3, 22, 13, 50, 55, 571, DateTimeKind.Unspecified).AddTicks(9331), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "NVDA + Chrome: tab cycle escapes modal when DatePicker overlay opens. Repro steps attached to design QA doc.",
                            DueDate = new DateTimeOffset(new DateTime(2025, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IssueStatusId = new Guid("019d15d0-2453-7d39-a748-d4f6599e3014"),
                            IssueTypeId = new Guid("019d15d0-2453-7fa7-a25a-8e507733a5f0"),
                            Name = "Focus trap breaks inside nested Dialog",
                            ProjectId = new Guid("019d15d0-2453-7e73-978e-4a66d0d60d72")
                        },
                        new
                        {
                            Id = new Guid("019d15d0-2453-79a7-b4a1-586f179d42e7"),
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 3, 22, 13, 50, 55, 571, DateTimeKind.Unspecified).AddTicks(9333), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Map legacy palette to new token names; no visual change in light theme.",
                            IssueStatusId = new Guid("019d15d0-2453-7982-9a52-c2672dd071c3"),
                            IssueTypeId = new Guid("019d15d0-2453-790d-81fb-679d476151e5"),
                            Name = "Ship semantic color tokens for dark mode",
                            ProjectId = new Guid("019d15d0-2453-7e73-978e-4a66d0d60d72")
                        },
                        new
                        {
                            Id = new Guid("019d15d0-2453-7003-a60f-e785b7e0a5b5"),
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 3, 22, 13, 50, 55, 571, DateTimeKind.Unspecified).AddTicks(9344), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Vendor scheduled March maintenance; update sealed secrets and verify staging send.",
                            DueDate = new DateTimeOffset(new DateTime(2025, 3, 25, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IssueStatusId = new Guid("019d15d0-2453-7156-8d56-e8ad4e9fb210"),
                            IssueTypeId = new Guid("019d15d0-2453-71da-a7ec-b87bbd5dc5be"),
                            Name = "Rotate SMTP credentials in vault",
                            ProjectId = new Guid("019d15d0-2453-77aa-a1e1-fb8792d909a0")
                        },
                        new
                        {
                            Id = new Guid("019d15d0-2453-71a8-9080-e3eb2f8d7daa"),
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 3, 22, 13, 50, 55, 571, DateTimeKind.Unspecified).AddTicks(9345), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "One page: required sections, tone, and when to require human rewrite before merge.",
                            DueDate = new DateTimeOffset(new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IssueStatusId = new Guid("019d15d0-2453-7a14-928f-10399c976e06"),
                            IssueTypeId = new Guid("019d15d0-2453-7067-927a-0c0cf0b0ba58"),
                            Name = "Draft team guidelines for AI-generated PR descriptions",
                            ProjectId = new Guid("019d15d0-2453-7260-8f78-11bff16a4c51")
                        });
                });

            modelBuilder.Entity("TaskService.Domain.Entities.IssueStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(225)
                        .HasColumnType("character varying(225)");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("IssueStatus");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019d15d0-2453-733e-982b-cc29b085b551"),
                            Color = "#94A3B8",
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 3, 22, 13, 50, 55, 571, DateTimeKind.Unspecified).AddTicks(6663), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "To Do",
                            Position = 0,
                            ProjectId = new Guid("019d15d0-2453-7a57-8998-a9493767fd5c"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("019d15d0-2453-7415-b462-5eb7fb31a500"),
                            Color = "#3B82F6",
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 3, 22, 13, 50, 55, 571, DateTimeKind.Unspecified).AddTicks(7096), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "In Progress",
                            Position = 1,
                            ProjectId = new Guid("019d15d0-2453-7a57-8998-a9493767fd5c"),
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("019d15d0-2453-7dd0-a9d5-4853949a08ac"),
                            Color = "#A855F7",
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 3, 22, 13, 50, 55, 571, DateTimeKind.Unspecified).AddTicks(7098), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "In Review",
                            Position = 2,
                            ProjectId = new Guid("019d15d0-2453-7a57-8998-a9493767fd5c"),
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("019d15d0-2453-75ce-8a81-034b0f24caea"),
                            Color = "#22C55E",
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 3, 22, 13, 50, 55, 571, DateTimeKind.Unspecified).AddTicks(7100), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Done",
                            Position = 3,
                            ProjectId = new Guid("019d15d0-2453-7a57-8998-a9493767fd5c"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("019d15d0-2453-7d39-a748-d4f6599e3014"),
                            Color = "#94A3B8",
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 3, 22, 13, 50, 55, 571, DateTimeKind.Unspecified).AddTicks(7852), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Backlog",
                            Position = 0,
                            ProjectId = new Guid("019d15d0-2453-7e73-978e-4a66d0d60d72"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("019d15d0-2453-7982-9a52-c2672dd071c3"),
                            Color = "#22C55E",
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 3, 22, 13, 50, 55, 571, DateTimeKind.Unspecified).AddTicks(7854), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Released",
                            Position = 1,
                            ProjectId = new Guid("019d15d0-2453-7e73-978e-4a66d0d60d72"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("019d15d0-2453-7156-8d56-e8ad4e9fb210"),
                            Color = "#94A3B8",
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 3, 22, 13, 50, 55, 571, DateTimeKind.Unspecified).AddTicks(7858), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "To Do",
                            Position = 0,
                            ProjectId = new Guid("019d15d0-2453-77aa-a1e1-fb8792d909a0"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("019d15d0-2453-70c3-bf99-c5cd1181900c"),
                            Color = "#22C55E",
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 3, 22, 13, 50, 55, 571, DateTimeKind.Unspecified).AddTicks(7859), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Done",
                            Position = 1,
                            ProjectId = new Guid("019d15d0-2453-77aa-a1e1-fb8792d909a0"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("019d15d0-2453-7a14-928f-10399c976e06"),
                            Color = "#94A3B8",
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 3, 22, 13, 50, 55, 571, DateTimeKind.Unspecified).AddTicks(7863), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "To Do",
                            Position = 0,
                            ProjectId = new Guid("019d15d0-2453-7260-8f78-11bff16a4c51"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("019d15d0-2453-7c75-96c8-a2df8c4c8cba"),
                            Color = "#22C55E",
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 3, 22, 13, 50, 55, 571, DateTimeKind.Unspecified).AddTicks(7864), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Done",
                            Position = 1,
                            ProjectId = new Guid("019d15d0-2453-7260-8f78-11bff16a4c51"),
                            Type = 2
                        });
                });

            modelBuilder.Entity("TaskService.Domain.Entities.IssueType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(225)
                        .HasColumnType("character varying(225)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("IssueType");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019d15d0-2453-7aa0-abb6-29a434a8748c"),
                            Color = "#EF4444",
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 3, 22, 13, 50, 55, 571, DateTimeKind.Unspecified).AddTicks(7710), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Bug",
                            ProjectId = new Guid("019d15d0-2453-7a57-8998-a9493767fd5c")
                        },
                        new
                        {
                            Id = new Guid("019d15d0-2453-73c7-ba12-42afb64f3541"),
                            Color = "#0EA5E9",
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 3, 22, 13, 50, 55, 571, DateTimeKind.Unspecified).AddTicks(7846), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Feature",
                            ProjectId = new Guid("019d15d0-2453-7a57-8998-a9493767fd5c")
                        },
                        new
                        {
                            Id = new Guid("019d15d0-2453-7d9f-bfaa-133df11a0f3d"),
                            Color = "#64748B",
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 3, 22, 13, 50, 55, 571, DateTimeKind.Unspecified).AddTicks(7847), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Chore",
                            ProjectId = new Guid("019d15d0-2453-7a57-8998-a9493767fd5c")
                        },
                        new
                        {
                            Id = new Guid("019d15d0-2453-790d-81fb-679d476151e5"),
                            Color = "#6366F1",
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 3, 22, 13, 50, 55, 571, DateTimeKind.Unspecified).AddTicks(7855), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Task",
                            ProjectId = new Guid("019d15d0-2453-7e73-978e-4a66d0d60d72")
                        },
                        new
                        {
                            Id = new Guid("019d15d0-2453-7fa7-a25a-8e507733a5f0"),
                            Color = "#F97316",
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 3, 22, 13, 50, 55, 571, DateTimeKind.Unspecified).AddTicks(7856), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Bug",
                            ProjectId = new Guid("019d15d0-2453-7e73-978e-4a66d0d60d72")
                        },
                        new
                        {
                            Id = new Guid("019d15d0-2453-71da-a7ec-b87bbd5dc5be"),
                            Color = "#0EA5E9",
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 3, 22, 13, 50, 55, 571, DateTimeKind.Unspecified).AddTicks(7862), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Task",
                            ProjectId = new Guid("019d15d0-2453-77aa-a1e1-fb8792d909a0")
                        },
                        new
                        {
                            Id = new Guid("019d15d0-2453-7067-927a-0c0cf0b0ba58"),
                            Color = "#64748B",
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 3, 22, 13, 50, 55, 571, DateTimeKind.Unspecified).AddTicks(7865), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Task",
                            ProjectId = new Guid("019d15d0-2453-7260-8f78-11bff16a4c51")
                        });
                });

            modelBuilder.Entity("TaskService.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("FinishDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(225)
                        .HasColumnType("character varying(225)");

                    b.Property<DateTimeOffset?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019d15d0-2453-7a57-8998-a9493767fd5c"),
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 3, 22, 13, 50, 55, 571, DateTimeKind.Unspecified).AddTicks(2777), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "ASP.NET Core service for workspaces, projects, issues, and notifications. Exposes REST APIs consumed by the web client.",
                            Name = "taskorium-api",
                            WorkspaceId = new Guid("019d15d0-2453-745a-a1fe-5fc6e1fa16f3")
                        },
                        new
                        {
                            Id = new Guid("019d15d0-2453-7e73-978e-4a66d0d60d72"),
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 3, 22, 13, 50, 55, 571, DateTimeKind.Unspecified).AddTicks(2909), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Open-source React component library shared across Taskorium frontends: layout primitives, forms, and accessibility-tested patterns.",
                            Name = "ui-kit",
                            WorkspaceId = new Guid("019d15d0-2453-745a-a1fe-5fc6e1fa16f3")
                        },
                        new
                        {
                            Id = new Guid("019d15d0-2453-77aa-a1e1-fb8792d909a0"),
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 3, 22, 13, 50, 55, 571, DateTimeKind.Unspecified).AddTicks(2911), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Outbox-backed worker that delivers email and in-app notifications with retry policies and idempotent handlers.",
                            Name = "taskorium-notify",
                            WorkspaceId = new Guid("019d15d0-2453-745a-a1fe-5fc6e1fa16f3")
                        },
                        new
                        {
                            Id = new Guid("019d15d0-2453-7260-8f78-11bff16a4c51"),
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 3, 22, 13, 50, 55, 571, DateTimeKind.Unspecified).AddTicks(2912), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Pilot: lint prompts, CI gates, and review checklists for teams adopting AI-assisted coding without bypassing quality bars.",
                            Name = "ai-dev-workflow",
                            WorkspaceId = new Guid("019d15d0-2452-7cc1-a65b-0f8033cc28c9")
                        },
                        new
                        {
                            Id = new Guid("019d15d0-2453-7ba7-852b-a51cfab3f744"),
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 3, 22, 13, 50, 55, 571, DateTimeKind.Unspecified).AddTicks(2917), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Rewrite onboarding and API reference for the next major release; align examples with current OpenAPI spec.",
                            Name = "docs-refresh",
                            WorkspaceId = new Guid("019d15d0-2452-7cc1-a65b-0f8033cc28c9")
                        },
                        new
                        {
                            Id = new Guid("019d15d0-2453-7f20-bbb4-006c9d331704"),
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 3, 22, 13, 50, 55, 571, DateTimeKind.Unspecified).AddTicks(2928), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Track removal of deprecated endpoints and migration of remaining consumers to v2 APIs.",
                            Name = "legacy-cleanup",
                            WorkspaceId = new Guid("019d15d0-2453-7e36-8ba8-9de394b7403b")
                        },
                        new
                        {
                            Id = new Guid("019d15d0-2453-7446-bf75-013b1242d10d"),
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 3, 22, 13, 50, 55, 571, DateTimeKind.Unspecified).AddTicks(2929), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Time-boxed prototype: WebSocket presence and optimistic updates for the board view.",
                            Name = "spike-realtime-board",
                            WorkspaceId = new Guid("019d15d0-2453-7e36-8ba8-9de394b7403b")
                        });
                });

            modelBuilder.Entity("TaskService.Domain.Entities.ProjectMember", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProjectId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectMembers");

                    b.HasData(
                        new
                        {
                            ProjectId = new Guid("019d15d0-2453-7a57-8998-a9493767fd5c"),
                            UserId = new Guid("019d15d0-2452-72aa-a7bd-1805328e4efa"),
                            JoinedAt = new DateTimeOffset(new DateTime(2025, 1, 8, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Role = "Member"
                        },
                        new
                        {
                            ProjectId = new Guid("019d15d0-2453-7a57-8998-a9493767fd5c"),
                            UserId = new Guid("019d15d0-2452-7c53-a3d0-d4c7853bc4fa"),
                            JoinedAt = new DateTimeOffset(new DateTime(2025, 1, 8, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Role = "Admin"
                        },
                        new
                        {
                            ProjectId = new Guid("019d15d0-2453-7a57-8998-a9493767fd5c"),
                            UserId = new Guid("019d15d0-2452-7488-8f7e-1ae7d2b67617"),
                            JoinedAt = new DateTimeOffset(new DateTime(2025, 1, 8, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Role = "Member"
                        },
                        new
                        {
                            ProjectId = new Guid("019d15d0-2453-7e73-978e-4a66d0d60d72"),
                            UserId = new Guid("019d15d0-2452-72aa-a7bd-1805328e4efa"),
                            JoinedAt = new DateTimeOffset(new DateTime(2025, 1, 8, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Role = "Member"
                        },
                        new
                        {
                            ProjectId = new Guid("019d15d0-2453-7e73-978e-4a66d0d60d72"),
                            UserId = new Guid("019d15d0-2452-7c53-a3d0-d4c7853bc4fa"),
                            JoinedAt = new DateTimeOffset(new DateTime(2025, 1, 8, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Role = "Admin"
                        },
                        new
                        {
                            ProjectId = new Guid("019d15d0-2453-77aa-a1e1-fb8792d909a0"),
                            UserId = new Guid("019d15d0-2452-7488-8f7e-1ae7d2b67617"),
                            JoinedAt = new DateTimeOffset(new DateTime(2025, 1, 8, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Role = "Admin"
                        },
                        new
                        {
                            ProjectId = new Guid("019d15d0-2453-77aa-a1e1-fb8792d909a0"),
                            UserId = new Guid("019d15d0-2452-72aa-a7bd-1805328e4efa"),
                            JoinedAt = new DateTimeOffset(new DateTime(2025, 1, 8, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Role = "Member"
                        });
                });

            modelBuilder.Entity("TaskService.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(225)
                        .HasColumnType("character varying(225)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("KeycloakId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(225)
                        .HasColumnType("character varying(225)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019d15d0-2452-7079-a291-fd51e37e4aa8"),
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 3, 22, 13, 50, 55, 570, DateTimeKind.Unspecified).AddTicks(7879), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "ivan.petrov@taskorium.local",
                            FullName = "Ivan Petrov",
                            KeycloakId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Username = "ivan.petrov"
                        },
                        new
                        {
                            Id = new Guid("019d15d0-2452-72aa-a7bd-1805328e4efa"),
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 3, 22, 13, 50, 55, 570, DateTimeKind.Unspecified).AddTicks(8825), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "peter.sokolov@taskorium.local",
                            FullName = "Peter Sokolov",
                            KeycloakId = new Guid("20000000-0000-0000-0000-000000000002"),
                            Username = "peter.sokolov"
                        },
                        new
                        {
                            Id = new Guid("019d15d0-2452-7c53-a3d0-d4c7853bc4fa"),
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 3, 22, 13, 50, 55, 570, DateTimeKind.Unspecified).AddTicks(8838), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "kirill.volkov@taskorium.local",
                            FullName = "Kirill Volkov",
                            KeycloakId = new Guid("30000000-0000-0000-0000-000000000003"),
                            Username = "kirill.volkov"
                        },
                        new
                        {
                            Id = new Guid("019d15d0-2452-7488-8f7e-1ae7d2b67617"),
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 3, 22, 13, 50, 55, 570, DateTimeKind.Unspecified).AddTicks(8855), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "alexey.nikitin@taskorium.local",
                            FullName = "Alexey Nikitin",
                            KeycloakId = new Guid("40000000-0000-0000-0000-000000000004"),
                            Username = "alexey.nikitin"
                        });
                });

            modelBuilder.Entity("TaskService.Domain.Entities.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(225)
                        .HasColumnType("character varying(225)");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Workspaces");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019d15d0-2452-7cc1-a65b-0f8033cc28c9"),
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 3, 22, 13, 50, 55, 571, DateTimeKind.Unspecified).AddTicks(675), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Personal",
                            OwnerId = new Guid("019d15d0-2452-7079-a291-fd51e37e4aa8")
                        },
                        new
                        {
                            Id = new Guid("019d15d0-2453-745a-a1fe-5fc6e1fa16f3"),
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 3, 22, 13, 50, 55, 571, DateTimeKind.Unspecified).AddTicks(980), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Taskorium",
                            OwnerId = new Guid("019d15d0-2452-7079-a291-fd51e37e4aa8")
                        },
                        new
                        {
                            Id = new Guid("019d15d0-2453-7e36-8ba8-9de394b7403b"),
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 3, 22, 13, 50, 55, 571, DateTimeKind.Unspecified).AddTicks(982), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Sandbox",
                            OwnerId = new Guid("019d15d0-2452-7079-a291-fd51e37e4aa8")
                        });
                });

            modelBuilder.Entity("TaskService.Domain.Entities.WorkspaceMember", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId", "WorkspaceId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("WorkspaceMembers");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("019d15d0-2452-7079-a291-fd51e37e4aa8"),
                            WorkspaceId = new Guid("019d15d0-2452-7cc1-a65b-0f8033cc28c9"),
                            JoinedAt = new DateTimeOffset(new DateTime(2025, 1, 8, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Role = "Admin"
                        },
                        new
                        {
                            UserId = new Guid("019d15d0-2452-72aa-a7bd-1805328e4efa"),
                            WorkspaceId = new Guid("019d15d0-2452-7cc1-a65b-0f8033cc28c9"),
                            JoinedAt = new DateTimeOffset(new DateTime(2025, 1, 8, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Role = "Member"
                        },
                        new
                        {
                            UserId = new Guid("019d15d0-2452-7079-a291-fd51e37e4aa8"),
                            WorkspaceId = new Guid("019d15d0-2453-745a-a1fe-5fc6e1fa16f3"),
                            JoinedAt = new DateTimeOffset(new DateTime(2025, 1, 8, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Role = "Admin"
                        },
                        new
                        {
                            UserId = new Guid("019d15d0-2452-72aa-a7bd-1805328e4efa"),
                            WorkspaceId = new Guid("019d15d0-2453-745a-a1fe-5fc6e1fa16f3"),
                            JoinedAt = new DateTimeOffset(new DateTime(2025, 1, 8, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Role = "Member"
                        },
                        new
                        {
                            UserId = new Guid("019d15d0-2452-7c53-a3d0-d4c7853bc4fa"),
                            WorkspaceId = new Guid("019d15d0-2453-745a-a1fe-5fc6e1fa16f3"),
                            JoinedAt = new DateTimeOffset(new DateTime(2025, 1, 8, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Role = "Admin"
                        },
                        new
                        {
                            UserId = new Guid("019d15d0-2452-7488-8f7e-1ae7d2b67617"),
                            WorkspaceId = new Guid("019d15d0-2453-745a-a1fe-5fc6e1fa16f3"),
                            JoinedAt = new DateTimeOffset(new DateTime(2025, 1, 8, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Role = "Viewer"
                        },
                        new
                        {
                            UserId = new Guid("019d15d0-2452-7488-8f7e-1ae7d2b67617"),
                            WorkspaceId = new Guid("019d15d0-2453-7e36-8ba8-9de394b7403b"),
                            JoinedAt = new DateTimeOffset(new DateTime(2025, 1, 8, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("TaskService.Domain.Entities.Attachment", b =>
                {
                    b.HasOne("TaskService.Domain.Entities.Issue", null)
                        .WithMany()
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaskService.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UploaderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskService.Domain.Entities.Issue", b =>
                {
                    b.HasOne("TaskService.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskService.Domain.Entities.IssueStatus", b =>
                {
                    b.HasOne("TaskService.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskService.Domain.Entities.IssueType", b =>
                {
                    b.HasOne("TaskService.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskService.Domain.Entities.Project", b =>
                {
                    b.HasOne("TaskService.Domain.Entities.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskService.Domain.Entities.ProjectMember", b =>
                {
                    b.HasOne("TaskService.Domain.Entities.Project", null)
                        .WithMany("ProjectMembers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaskService.Domain.Entities.User", null)
                        .WithMany("ProjectMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskService.Domain.Entities.Workspace", b =>
                {
                    b.HasOne("TaskService.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerId");
                });

            modelBuilder.Entity("TaskService.Domain.Entities.WorkspaceMember", b =>
                {
                    b.HasOne("TaskService.Domain.Entities.User", null)
                        .WithMany("WorkspaceMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskService.Domain.Entities.Workspace", null)
                        .WithMany("WorkspaceMembers")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskService.Domain.Entities.Project", b =>
                {
                    b.Navigation("ProjectMembers");
                });

            modelBuilder.Entity("TaskService.Domain.Entities.User", b =>
                {
                    b.Navigation("ProjectMembers");

                    b.Navigation("WorkspaceMembers");
                });

            modelBuilder.Entity("TaskService.Domain.Entities.Workspace", b =>
                {
                    b.Navigation("WorkspaceMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
