// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskService.Infrastructure.Persistence;

#nullable disable

namespace TaskService.Infrastructure.Migrations
{
    [DbContext(typeof(TaskServiceDbContext))]
    partial class TaskServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IssueTag", b =>
                {
                    b.Property<Guid>("IssuesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("uuid");

                    b.HasKey("IssuesId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("IssueTag");
                });

            modelBuilder.Entity("TaskService.Domain.Entities.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("UploaderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.HasIndex("UploaderId");

                    b.ToTable("Attachments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019d399c-2a7a-75d1-b674-6b5a40ca34a7"),
                            IssueId = new Guid("019d399c-2a78-797f-a73a-3f9aa697f117"),
                            StoragePath = "attachments/mob-1/wireframe.png",
                            UploaderId = new Guid("019d399c-2a77-77cf-8fa0-3b54e54910ff")
                        },
                        new
                        {
                            Id = new Guid("019d399c-2a7a-7ccf-aee6-3614b1d0492a"),
                            IssueId = new Guid("019d399c-2a7a-7ece-a77a-aff51fdd2458"),
                            StoragePath = "attachments/mob-2/logcat.txt",
                            UploaderId = new Guid("019d399c-2a77-7d11-bbd4-db8c27757b25")
                        });
                });

            modelBuilder.Entity("TaskService.Domain.Entities.Issue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IssuePriority")
                        .HasColumnType("integer");

                    b.Property<Guid>("IssueStatusId")
                        .HasColumnType("uuid");

                    b.Property<int>("IssueType")
                        .HasColumnType("integer");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(225)
                        .HasColumnType("character varying(225)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ResolvedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Issues");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019d399c-2a78-797f-a73a-3f9aa697f117"),
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 3, 29, 12, 40, 29, 48, DateTimeKind.Unspecified).AddTicks(3808), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Implement email and SSO login.",
                            DueDate = new DateTimeOffset(new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IssuePriority = 3,
                            IssueStatusId = new Guid("019d399c-2a78-7197-b808-733763f23a62"),
                            IssueType = 0,
                            Key = "MOB-1",
                            Name = "Login screen",
                            ProjectId = new Guid("019d399c-2a77-7614-a948-620f1191a855")
                        },
                        new
                        {
                            Id = new Guid("019d399c-2a7a-7ece-a77a-aff51fdd2458"),
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 3, 29, 12, 40, 29, 50, DateTimeKind.Unspecified).AddTicks(5341), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Reproduces on Android 14.",
                            DueDate = new DateTimeOffset(new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IssuePriority = 4,
                            IssueStatusId = new Guid("019d399c-2a78-7f43-9db3-0bf290c89ca6"),
                            IssueType = 2,
                            Key = "MOB-2",
                            Name = "Crash on cold start",
                            ProjectId = new Guid("019d399c-2a77-7614-a948-620f1191a855")
                        },
                        new
                        {
                            Id = new Guid("019d399c-2a7a-7ebc-8553-4464fb17c356"),
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 3, 29, 12, 40, 29, 50, DateTimeKind.Unspecified).AddTicks(5567), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Finalize strings for v1.",
                            IssuePriority = 1,
                            IssueStatusId = new Guid("019d399c-2a78-774b-9570-9e62bc08f0a0"),
                            IssueType = 1,
                            Key = "MOB-3",
                            Name = "Push notification copy",
                            ProjectId = new Guid("019d399c-2a77-7614-a948-620f1191a855")
                        });
                });

            modelBuilder.Entity("TaskService.Domain.Entities.IssueStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(225)
                        .HasColumnType("character varying(225)");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("IssueStatus");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019d399c-2a78-7f43-9db3-0bf290c89ca6"),
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 3, 29, 12, 40, 29, 48, DateTimeKind.Unspecified).AddTicks(1555), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Backlog",
                            Position = 0,
                            ProjectId = new Guid("019d399c-2a77-7614-a948-620f1191a855"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("019d399c-2a78-7197-b808-733763f23a62"),
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 3, 29, 12, 40, 29, 48, DateTimeKind.Unspecified).AddTicks(1784), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "In progress",
                            Position = 1,
                            ProjectId = new Guid("019d399c-2a77-7614-a948-620f1191a855"),
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("019d399c-2a78-774b-9570-9e62bc08f0a0"),
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 3, 29, 12, 40, 29, 48, DateTimeKind.Unspecified).AddTicks(1786), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Done",
                            Position = 2,
                            ProjectId = new Guid("019d399c-2a77-7614-a948-620f1191a855"),
                            Type = 2
                        });
                });

            modelBuilder.Entity("TaskService.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("FinishDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(225)
                        .HasColumnType("character varying(225)");

                    b.Property<DateTimeOffset?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019d399c-2a77-7614-a948-620f1191a855"),
                            Abbreviation = "MOB",
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 3, 29, 12, 40, 29, 47, DateTimeKind.Unspecified).AddTicks(9498), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Customer-facing iOS and Android app.",
                            Name = "Mobile client",
                            WorkspaceId = new Guid("019d399c-2a77-79fd-9ff7-acf17ea6bc2e")
                        });
                });

            modelBuilder.Entity("TaskService.Domain.Entities.ProjectMember", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProjectId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectMembers");

                    b.HasData(
                        new
                        {
                            ProjectId = new Guid("019d399c-2a77-7614-a948-620f1191a855"),
                            UserId = new Guid("019d399c-2a77-77cf-8fa0-3b54e54910ff"),
                            JoinedAt = new DateTimeOffset(new DateTime(2026, 1, 15, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Role = "Creator"
                        },
                        new
                        {
                            ProjectId = new Guid("019d399c-2a77-7614-a948-620f1191a855"),
                            UserId = new Guid("019d399c-2a77-7d11-bbd4-db8c27757b25"),
                            JoinedAt = new DateTimeOffset(new DateTime(2026, 1, 16, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Role = "Member"
                        },
                        new
                        {
                            ProjectId = new Guid("019d399c-2a77-7614-a948-620f1191a855"),
                            UserId = new Guid("019d399c-2a77-7365-b1a4-e737e821d4fb"),
                            JoinedAt = new DateTimeOffset(new DateTime(2026, 1, 18, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Role = "Viewer"
                        });
                });

            modelBuilder.Entity("TaskService.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(225)
                        .HasColumnType("character varying(225)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("TaskService.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(225)
                        .HasColumnType("character varying(225)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("KeycloakId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(225)
                        .HasColumnType("character varying(225)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019d399c-2a77-77cf-8fa0-3b54e54910ff"),
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 3, 29, 12, 40, 29, 47, DateTimeKind.Unspecified).AddTicks(4107), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "alice@example.com",
                            FullName = "Alice Anderson",
                            KeycloakId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1"),
                            Username = "alice"
                        },
                        new
                        {
                            Id = new Guid("019d399c-2a77-7d11-bbd4-db8c27757b25"),
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 3, 29, 12, 40, 29, 47, DateTimeKind.Unspecified).AddTicks(5202), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "bob@example.com",
                            FullName = "Bob Brown",
                            KeycloakId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb2"),
                            Username = "bob"
                        },
                        new
                        {
                            Id = new Guid("019d399c-2a77-7365-b1a4-e737e821d4fb"),
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 3, 29, 12, 40, 29, 47, DateTimeKind.Unspecified).AddTicks(5205), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "carol@example.com",
                            FullName = "Carol Chen",
                            KeycloakId = new Guid("cccccccc-cccc-cccc-cccc-ccccccccccc3"),
                            Username = "carol"
                        });
                });

            modelBuilder.Entity("TaskService.Domain.Entities.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(225)
                        .HasColumnType("character varying(225)");

                    b.HasKey("Id");

                    b.ToTable("Workspaces");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019d399c-2a77-79fd-9ff7-acf17ea6bc2e"),
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 3, 29, 12, 40, 29, 47, DateTimeKind.Unspecified).AddTicks(6992), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Acme Workspace"
                        });
                });

            modelBuilder.Entity("TaskService.Domain.Entities.WorkspaceMember", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId", "WorkspaceId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("WorkspaceMembers");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("019d399c-2a77-77cf-8fa0-3b54e54910ff"),
                            WorkspaceId = new Guid("019d399c-2a77-79fd-9ff7-acf17ea6bc2e"),
                            JoinedAt = new DateTimeOffset(new DateTime(2026, 1, 15, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Role = "Creator"
                        },
                        new
                        {
                            UserId = new Guid("019d399c-2a77-7d11-bbd4-db8c27757b25"),
                            WorkspaceId = new Guid("019d399c-2a77-79fd-9ff7-acf17ea6bc2e"),
                            JoinedAt = new DateTimeOffset(new DateTime(2026, 1, 16, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Role = "Admin"
                        },
                        new
                        {
                            UserId = new Guid("019d399c-2a77-7365-b1a4-e737e821d4fb"),
                            WorkspaceId = new Guid("019d399c-2a77-79fd-9ff7-acf17ea6bc2e"),
                            JoinedAt = new DateTimeOffset(new DateTime(2026, 1, 17, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Role = "Member"
                        });
                });

            modelBuilder.Entity("IssueTag", b =>
                {
                    b.HasOne("TaskService.Domain.Entities.Issue", null)
                        .WithMany()
                        .HasForeignKey("IssuesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskService.Domain.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskService.Domain.Entities.Attachment", b =>
                {
                    b.HasOne("TaskService.Domain.Entities.Issue", null)
                        .WithMany()
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaskService.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UploaderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskService.Domain.Entities.Issue", b =>
                {
                    b.HasOne("TaskService.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskService.Domain.Entities.IssueStatus", b =>
                {
                    b.HasOne("TaskService.Domain.Entities.Project", null)
                        .WithMany("Statuses")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskService.Domain.Entities.Project", b =>
                {
                    b.HasOne("TaskService.Domain.Entities.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskService.Domain.Entities.ProjectMember", b =>
                {
                    b.HasOne("TaskService.Domain.Entities.Project", null)
                        .WithMany("ProjectMembers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaskService.Domain.Entities.User", null)
                        .WithMany("ProjectMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskService.Domain.Entities.Tag", b =>
                {
                    b.HasOne("TaskService.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskService.Domain.Entities.WorkspaceMember", b =>
                {
                    b.HasOne("TaskService.Domain.Entities.User", null)
                        .WithMany("WorkspaceMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskService.Domain.Entities.Workspace", null)
                        .WithMany("WorkspaceMembers")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskService.Domain.Entities.Project", b =>
                {
                    b.Navigation("ProjectMembers");

                    b.Navigation("Statuses");
                });

            modelBuilder.Entity("TaskService.Domain.Entities.User", b =>
                {
                    b.Navigation("ProjectMembers");

                    b.Navigation("WorkspaceMembers");
                });

            modelBuilder.Entity("TaskService.Domain.Entities.Workspace", b =>
                {
                    b.Navigation("WorkspaceMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
