name: Taskorium workflow

on:
  pull_request:
    branches: [ "main", "dev" ]
    paths:
      - 'src/**'
      - '.github/workflows/workflow.yml'

jobs:
  format-build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Show SDK info
        run: dotnet --info

      - name: Restore dependencies
        working-directory: ./src/backend
        run: dotnet restore Taskorium.slnx

      - name: Format code
        working-directory: ./src/backend
        run: dotnet format Taskorium.slnx --no-restore --verify-no-changes

      - name: Build
        working-directory: ./src/backend
        run: dotnet build Taskorium.slnx --no-restore

      - name: Test
        working-directory: ./src/backend/Services/Task/TaskService.Tests
        run: dotnet test --no-build --verbosity normal

      - name: Notify the commit on Telegram
        uses: EverythingSuckz/github-telegram-notify@main
        with:
          bot_token: '${{ secrets.BOT_TOKEN }}'
          chat_id: '${{ secrets.CHAT_ID }}'